# Generated by Django 6.1 on 2026-08-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, help_text='Ward the patient currently occupies (free text).', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_assignment', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], help_text='Denormalized at assignment time so it stays stable if staff.role later changes.', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, help_text='Soft-deactivate to end an assignment; never delete, so history survives.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='staff.staff')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('patient', 'staff', 'role_in_assignment'), name='unique_active_patient_staff_role_assignment')],
            },
        ),
    ]
