# Generated by Django 6.1 on 2026-08-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCategoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Identity'), (2, 'Administrative/Billing'), (3, 'Vital Signs & Routine Observations'), (4, 'Diagnosis & Medical History'), (5, 'Medication & Prescriptions'), (6, 'Allergies'), (7, 'General Lab Results'), (8, 'Highly Sensitive Test Results'), (9, 'Mental Health Records'), (10, 'Reproductive Health Records'), (11, 'Surgical/Procedure History'), (12, 'Nursing & Care Notes'), (13, 'Imaging/Radiology')])),
                ('content', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_records', to='patients.patient')),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'category'), name='unique_patient_category')],
            },
        ),
    ]
