# Generated by Django 6.1 on 2026-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientcategoryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.CharField(blank=True, choices=[('general_male', 'General Male Ward'), ('general_female', 'General Female Ward'), ('surgical', 'Surgical Ward'), ('emergency', 'Emergency Ward')], help_text='Ward the patient currently occupies.', max_length=128),
        ),
    ]
