# Generated by Django 6.1 on 2026-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('outpatient', 'Outpatient')], help_text='Current-state label (Admitted/Discharged/Outpatient). Blank means not yet set.', max_length=32),
        ),
    ]
