# Generated by Django 6.1 on 2026-09-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patient_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_template', models.TextField()),
                ('enrolled_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by_staff_id', models.CharField(blank=True, default='', max_length=64)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_template', to='patients.patient')),
            ],
        ),
    ]
