# Generated by Django 6.1 on 2026-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ACCESS_DENIED', 'Access denied'), ('LOGIN_LOCKOUT', 'Login lockout'), ('STEP_UP_FAILED', 'Step-up verification failed')], max_length=32)),
                ('staff_id', models.CharField(blank=True, default='', max_length=64)),
                ('staff_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('staff_role', models.CharField(blank=True, default='', max_length=32)),
                ('patient_hospital_number', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ledger_sequence', models.IntegerField(blank=True, null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_staff_id', models.CharField(blank=True, default='', max_length=64)),
                ('acknowledgement_note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
    ]
