"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env (gitignored — SECRET_KEY, WORKSTATION_NETWORK_SEGMENT).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to an obviously-insecure dev key only if .env is missing entirely.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only-set-env-file')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe for the public Render deploy); set DEBUG=True in
# backend/.env for local dev.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Wide open on purpose: this never carries real patient data (see CLAUDE.md
# "Enrollment data"), and the deploy target (Render subdomain) isn't known
# ahead of time.
ALLOWED_HOSTS = ['*']

# Static per-workstation network segment (see .env / CLAUDE.md Contextual module).
WORKSTATION_NETWORK_SEGMENT = os.environ.get('WORKSTATION_NETWORK_SEGMENT', 'unknown')

# Ledger live-feed "explain with AI" feature (see .env / ledger/gemini.py).
# Unset locally means that feature returns a friendly 502, not a crash.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.6-flash')

# Login brute-force lockout (added 2026-09-06 -- see access/services.py).
# An account is locked while it has at least LOGIN_MAX_FAILED_ATTEMPTS failed
# attempts inside the last LOGIN_LOCKOUT_MINUTES; the lock then expires on its
# own as those failures age out of the window (an admin can also clear it
# early -- staff.views.StaffUnlockView).
LOGIN_MAX_FAILED_ATTEMPTS = int(os.environ.get('LOGIN_MAX_FAILED_ATTEMPTS', '5'))
LOGIN_LOCKOUT_MINUTES = int(os.environ.get('LOGIN_LOCKOUT_MINUTES', '15'))

# Step-up verification via device biometrics (added 2026-09-06, replacing a
# typed PIN -- see access/views.py, scoring/views.py). WebAuthn ties a
# credential to the origin the BROWSER believes it's on -- that's the
# FRONTEND's origin (Vercel), not this backend's (Render), even though
# verification happens here. Getting this wrong is the classic WebAuthn
# deployment mistake: set these to the real frontend domain once one exists,
# not the backend's. Locally both default to localhost, which just works
# regardless of the two dev servers running on different ports.
WEBAUTHN_RP_ID = os.environ.get('WEBAUTHN_RP_ID', 'localhost')
WEBAUTHN_RP_NAME = os.environ.get('WEBAUTHN_RP_NAME', 'MedGuard')
WEBAUTHN_ORIGIN = os.environ.get('WEBAUTHN_ORIGIN', 'http://localhost:5173')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local apps (dependency order: staff -> patients -> access -> captures -> scoring -> ledger)
    'staff',
    'patients',
    'access',
    'captures',
    'scoring',
    'ledger',
    # Security alerts (added 2026-09-06) -- raised by access/scoring, read by the
    # Security dashboard. Depends on nothing (denormalized fields, no FKs), so it
    # sits at the end of the order above.
    'alerts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: the Vite dev server, any LAN address (teammate phones on the same
# Wi-Fi), and the Vercel-hosted frontend (prod + preview deploys).
#
# Port is a range, not a fixed 5173: Vite auto-increments to 5174/5175/... when an
# earlier port is already taken (e.g. another dev server left running), so a
# fixed-port allowlist breaks CORS the moment that happens locally.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^http://localhost:\d{2,5}$',
    r'^http://\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{2,5}$',
    r'^https://.*\.vercel\.app$',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'access.authentication.AccessSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Uses Postgres when DATABASE_URL is set (Render), falls back to local SQLite
# (dev machine) otherwise.
#
# `ledger` is a second, separate database (see CLAUDE.md Security Ledger: "store
# separately from the main application's database... so a compromised main system
# can't edit its own trail"). It defaults to a second local SQLite file; set
# LEDGER_DATABASE_URL to point it at a real separate database (its own Postgres
# instance, ideally a different provider than `default`'s) once one exists — no code
# changes needed, see ledger/db_router.py.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    ),
    'ledger': dj_database_url.config(
        env='LEDGER_DATABASE_URL',
        default=f"sqlite:///{BASE_DIR / 'ledger.sqlite3'}",
        conn_max_age=600,
    ),
}

DATABASE_ROUTERS = ['ledger.db_router.LedgerRouter']


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded staff photos (see staff.Staff.photo, added 2026-09-05). Served via
# config/urls.py's static() helper in DEBUG only -- local-disk storage, so this
# won't survive a redeploy on Render's ephemeral free-tier disk (accepted
# tradeoff, per the user -- swap to real object storage later if needed).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Manifest storage needs `collectstatic` to have run (Render build step does
# this); locally in dev, Django's own default serves static files fine.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}
