# Generated by Django 6.1 on 2026-08-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystroke_events', models.JSONField(blank=True, default=list)),
                ('mouse_events', models.JSONField(blank=True, default=list)),
                ('touch_events', models.JSONField(blank=True, default=list)),
                ('keystroke_event_count', models.PositiveIntegerField(default=0)),
                ('mouse_event_count', models.PositiveIntegerField(default=0)),
                ('touch_event_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_capture', to='access.accesssession')),
            ],
        ),
        migrations.CreateModel(
            name='ContextualCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_duty_at_login', models.BooleanField()),
                ('ward_assignment_at_login', models.CharField(blank=True, max_length=128)),
                ('patient_assignment_status', models.CharField(choices=[('not_applicable', 'Not applicable (role has no assignment concept)'), ('no_patient_selected', 'No patient selected yet'), ('assigned', 'Specifically assigned to this patient'), ('same_ward_not_assigned', 'Same ward, not specifically assigned'), ('not_assigned_not_same_ward', 'Neither assigned nor same ward')], default='no_patient_selected', max_length=32)),
                ('patient_assignment_checked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_capture', to='access.accesssession')),
                ('target_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_captures', to='patients.patient')),
            ],
        ),
    ]
