# Generated by Django 6.1 on 2026-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavioralcapture',
            name='keystroke_event_count',
        ),
        migrations.RemoveField(
            model_name='behavioralcapture',
            name='keystroke_events',
        ),
        migrations.AddField(
            model_name='behavioralcapture',
            name='keystroke_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
