# Generated by Django 6.1 on 2026-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_remove_behavioralcapture_keystroke_event_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextualcapture',
            name='on_call_at_login',
            field=models.BooleanField(default=False, help_text='Snapshot of staff.on_call at login time (added 2026-08-29) -- same historical-accuracy reasoning as on_duty_at_login above.'),
        ),
    ]
