# Generated by Django 6.1 on 2026-08-24 23:30

import access.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=access.models.generate_session_token, editable=False, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('network_segment', models.CharField(blank=True, default='unknown', max_length=128)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='staff.staff')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
