# Generated by Django 6.1 on 2026-08-30 13:19

import access.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('staff', '0004_alter_staff_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeviceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('poll_token', models.CharField(default=access.models.generate_session_token, editable=False, max_length=64, unique=True)),
                ('session_token', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_device_requests', to='staff.staff')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('is_primary', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='staff.staff')),
            ],
            options={
                'ordering': ['-is_primary', '-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'device_id'), name='unique_device_per_staff')],
            },
        ),
    ]
