# Generated by Django 6.1 on 2026-09-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_loginattempt'),
        ('staff', '0008_remove_staff_step_up_pin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssession',
            name='webauthn_challenge',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='webauthn_challenge_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credential', to='access.device')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to='staff.staff')),
            ],
        ),
    ]
