# Generated by Django 6.1 on 2026-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_accesssession_webauthn_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sync_public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
