# Generated by Django 6.1 on 2026-09-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0005_device_sync_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(unique=True)),
                ('entries_synced', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_batches', to='access.device')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
