# Generated by Django 6.1 on 2026-08-24 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab technician'), ('clerk', 'Clerk')], max_length=32)),
                ('ward', models.CharField(blank=True, help_text='Ward this staff member is generally assigned to (free text, manually set).', max_length=128)),
                ('on_duty', models.BooleanField(default=False, help_text='Manually toggled on-duty status. Never computed by a scheduler.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text="Django auth user this staff member logs in as (reuses Django's built-in password hashing).", on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff member',
                'verbose_name_plural': 'Staff members',
            },
        ),
    ]
