# Generated by Django 6.1 on 2026-08-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab technician'), ('clerk', 'Clerk'), ('admin', 'Admin'), ('security_officer', 'Security officer')], max_length=32),
        ),
    ]
