# Generated by Django 6.1 on 2026-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='on_call',
            field=models.BooleanField(default=False, help_text="Manually toggled on-call status -- reachable/available even while off duty. Treated as equivalent to on_duty by the Doctor rule and BTG's availability gate (see scoring app, added 2026-08-29). Never computed."),
        ),
    ]
