# Generated by Django 6.1 on 2026-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_on_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ward',
            field=models.CharField(blank=True, choices=[('general_male', 'General Male Ward'), ('general_female', 'General Female Ward'), ('surgical', 'Surgical Ward'), ('emergency', 'Emergency Ward')], help_text='Ward this staff member is generally assigned to (manually set).', max_length=128),
        ),
    ]
