# Generated by Django 6.1 on 2026-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_staff_id', models.CharField(max_length=64)),
                ('actor_full_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('staff_created', 'Created'), ('staff_deactivated', 'Deactivated'), ('staff_reactivated', 'Reactivated'), ('staff_deleted', 'Deleted')], max_length=32)),
                ('target_staff_id', models.CharField(max_length=64)),
                ('target_full_name', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, default='', max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
