# Generated by Django 6.1 on 2026-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text="Self-uploaded profile photo (added 2026-09-05, per the user). Local disk storage -- fine for local dev/a single demo session, but Render's free tier disk is ephemeral, so this won't survive a backend redeploy there without swapping in real object storage later.", null=True, upload_to='staff_photos/'),
        ),
    ]
