# Generated by Django 6.1 on 2026-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='step_up_pin_hash',
            field=models.CharField(blank=True, default='', help_text="Hashed step-up PIN (added 2026-09-06). A second factor, separate from the login password, required to open records in the 40-69% REDUCED_ACCESS band -- see CLAUDE.md's band table. Hashed with Django's password hashers; the PIN itself is never stored. Blank means no PIN set, which fails closed: that staff member cannot complete step-up at all until an admin sets one.", max_length=128),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('staff_created', 'Created'), ('staff_deactivated', 'Deactivated'), ('staff_reactivated', 'Reactivated'), ('staff_deleted', 'Deleted'), ('staff_unlocked', 'Unlocked'), ('step_up_pin_set', 'Step-up PIN set')], max_length=32),
        ),
    ]
