# Generated by Django 6.1 on 2026-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_step_up_pin_hash_alter_adminactionlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='step_up_pin_hash',
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('staff_created', 'Created'), ('staff_deactivated', 'Deactivated'), ('staff_reactivated', 'Reactivated'), ('staff_deleted', 'Deleted'), ('staff_unlocked', 'Unlocked'), ('step_up_pin_set', 'Step-up PIN set (retired)')], max_length=32),
        ),
    ]
