# Generated by Django 6.1 on 2026-08-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('gate_passed', models.BooleanField()),
                ('score', models.FloatField()),
                ('score_band', models.CharField(choices=[('silent', 'Silent (90-100%)'), ('audited_deviation', 'Audited deviation (70-89%)'), ('reduced', 'Reduced (40-69%)'), ('denied', 'Denied (<40% or gate failed)')], max_length=32)),
                ('decision_type', models.CharField(choices=[('STANDARD_ACCESS', 'Standard access'), ('AUDITED_DEVIATION', 'Audited deviation'), ('REDUCED_ACCESS', 'Reduced access'), ('ACCESS_DENIED', 'Access denied')], max_length=32)),
                ('granted_categories', models.JSONField(blank=True, default=list)),
                ('nurse_path', models.CharField(blank=True, default='', max_length=16)),
                ('factor_breakdown', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_decisions', to='patients.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_decisions', to='access.accesssession')),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('keystroke_stats', models.JSONField(blank=True, default=dict)),
                ('mouse_stats', models.JSONField(blank=True, default=dict)),
                ('known_device_ids', models.JSONField(blank=True, default=list)),
                ('login_hour_stats', models.JSONField(blank=True, default=dict)),
                ('known_network_segments', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_baseline', to='staff.staff')),
            ],
        ),
    ]
