# Generated by Django 6.1 on 2026-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdecision',
            name='decision_type',
            field=models.CharField(choices=[('STANDARD_ACCESS', 'Standard access'), ('AUDITED_DEVIATION', 'Audited deviation'), ('REDUCED_ACCESS', 'Reduced access'), ('ACCESS_DENIED', 'Access denied'), ('EMERGENCY_OVERRIDE', 'Emergency override')], max_length=32),
        ),
        migrations.AlterField(
            model_name='accessdecision',
            name='gate_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessdecision',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessdecision',
            name='score_band',
            field=models.CharField(blank=True, choices=[('silent', 'Silent (90-100%)'), ('audited_deviation', 'Audited deviation (70-89%)'), ('reduced', 'Reduced (40-69%)'), ('denied', 'Denied (<40% or gate failed)')], max_length=32, null=True),
        ),
    ]
