# Generated by Django 6.1 on 2026-08-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_rename_nurse_path_to_role_rule_path'),
        ('staff', '0003_staff_on_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterModeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_mode_events', to='staff.staff')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
