# Generated by Django 6.1 on 2026-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_disastermodeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdecision',
            name='step_up_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='step_up_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='step_up_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
