# Generated by Django 6.1 on 2026-09-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_accessdecision_step_up_failed_attempts_and_more'),
        ('staff', '0008_remove_staff_step_up_pin_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepUpAssistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_requests', to='scoring.accessdecision')),
                ('requesting_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_assist_requests_made', to='staff.staff')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_up_assist_requests_resolved', to='staff.staff')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
