# Generated by Django 6.1 on 2026-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_stepupassistrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepupassistrequest',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
