# Generated by Django 6.1 on 2026-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('STANDARD_ACCESS', 'Standard access'), ('AUDITED_DEVIATION', 'Audited deviation'), ('REDUCED_ACCESS', 'Reduced access'), ('ACCESS_DENIED', 'Access denied'), ('EMERGENCY_OVERRIDE', 'Emergency override')], max_length=32)),
                ('staff_id', models.CharField(max_length=64)),
                ('staff_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('patient_hospital_number', models.CharField(blank=True, default='', max_length=64)),
                ('session_token', models.CharField(blank=True, default='', max_length=64)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
