# Generated by Django 6.1 on 2026-08-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='staff_role',
            field=models.CharField(blank=True, default='', help_text="Denormalized snapshot of Staff.role at write time (added 2026-08-30, for the Security Dashboard's staff-role breakdown chart) -- same reasoning as staff_full_name above, not part of the hash payload.", max_length=32),
        ),
    ]
